module.exports = products = [
  {
    name: "iPhone 9",
    images: "pexels-photo-1786433.jpeg",
    description: "An apple mobile which is nothing like apple",
    brand: "Apple",
    category: "smartphones",
    price: 549,
    countInStock: 3,
    rating: 3.69,
    reviews: 4,
  },
  {
    name: "iPhone 9",
    images: "pexels-photo-1786433.jpeg",
    description: "An apple mobile which is nothing like apple",
    brand: "Apple",
    category: "smartphones",
    price: 549,
    countInStock: 3,
    rating: 1,
    reviews: 4,
  },
  {
    name: "iPhone 9",
    images: "pexels-photo-1786433.jpeg",
    description: "An apple mobile which is nothing like apple",
    brand: "Apple",
    category: "smartphones",
    price: 549,
    countInStock: 0,
    rating: 4.29,
    reviews: 4,
  },
  {
    name: "iPhone 9",
    images: "pexels-photo-1786433.jpeg",
    description: "An apple mobile which is nothing like apple",
    brand: "Apple",
    category: "smartphones",
    price: 549,
    countInStock: 3,
    rating: 2.69,
    reviews: 1,
  },
  {
    name: "iPhone 9",
    images: "pexels-photo-788946.webp",
    description: "An apple mobile which is nothing like apple",
    brand: "Apple",
    category: "smartphones",
    price: 549,
    countInStock: 3,
    rating: 1.49,
    reviews: 4,
  },
]
